Update v2.yml add failed message and exit 1

diff --git a/.github/workflows/v2.yml b/.github/workflows/v2.yml
--- a/.github/workflows/v2.yml
+++ b/.github/workflows/v2.yml
@@ -19,8 +19,9 @@ jobs:
         view_files=$(find . -name "*.view.lkml")
 
         if [ -z "$view_files" ]; then
-          echo " No view files found"
-          exit 0
+          echo "🔻 No view files found!"
+          echo "::error::No view files found"
+          exit 1
         fi
         
         failed_views=""
@@ -33,8 +34,9 @@ jobs:
           dimension_count=$(grep -c "^\s*dimension" "$file" || true)
 
           if [ "dimension_count" -eq 0 ]; then
-            echo " $file has NO dim"
+            echo "🚫 FAILED $file has NO dim"
             failed_views="$failed_views $file"
+            exit 1
           else
             echo " $file has $dimension_count dim(s)"
           fi
@@ -43,12 +45,12 @@ jobs:
         #report result
         if [ -n "$failed_views" ]; then
           echo ""
-          echo " FAILED: These view have no dim:"
+          echo "🚫 FAILED: These view have no dim:"
           for view in $failed_views; do
             echo " - $view"
           done
           exit 1
         else
           echo ""
-          echo " SUCCESS"
+          echo "🚀 SUCCESS"
         fi
